mymessage: Message from server

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: pgssoft
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/schooldaily
    username: pgsuser
    password: '{cipher}AQBms1YytxwcLjF7sPoRXzEamvn8vI4lqe3xRRudMLgU+yE0qQDb0l471Lgnh5AhboCSSk7PFH94lA8p+zHiJcum4wHhqq6GOiQgK1OkWp6Cit6xADEdmJw0YyalK/GjUUs1m4qtJZfSD0m/0U8AF0acZrSZl5fmEaezGt/pFo7Jusa7lmCAJE8QiL7ZqWFRjo48c1c6FevmdamcTS+GE/5B6yD4PAwiZCytZRD4ZfiN3a9AphmTSaC7hOP5RSv2Juvg+cT9L4+gIZWJZYY4PGAWs220cQwGasIxPEr6wkkfiKWmZCM42TVz6xaUkTKMoVz1WpNscYyc4+WOOruvktdPbWgmMoZWlZzN2rrhwUdFfV/PxKPZLj0VNzhdfh5bQis='
    #password: pgspass
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true

logging.level.org.springframework: DEBUG

###social media###

#schooldaily2017@gmail.com/pgsadmin2017x2
facebook:
  client:
    clientId: 223400851399755
    clientSecret: 56588c70987a1dd0d4815367571a2469
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope:
      - publish_actions
  resource:
    userInfoUri: https://graph.facebook.com/me

#schooldaily2017@gmail.com/pgsadmin2017x2
github:
  client:
    clientId: 5fb1c9a2e16826c0a73b
    clientSecret: 08c043e884293474f11389bc66445a965ac71735
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
      - user:email
  resource:
    userInfoUri: https://api.github.com/user

#schooldaily2017@gmail.com/pgsadmin2017x2
google:
  client:
    clientId: 978955442750-toei3c6ngd3iid1u07j8as8gfb6kinmk.apps.googleusercontent.com
    clientSecret: SMgoi4tn9G_9B0WjHfoMVrOL
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true